# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('atividade_id', models.AutoField(primary_key=True, serialize=False)),
                ('atividade_nome', models.CharField(max_length=200)),
                ('atividade_descricao', models.TextField()),
                ('atividade_local', models.CharField(max_length=200)),
                ('atividade_data', models.DateField()),
                ('atividade_hora_inicio', models.TimeField()),
                ('atividade_hora_termino', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('evento_id', models.AutoField(primary_key=True, serialize=False)),
                ('evento_nome', models.CharField(max_length=200)),
                ('evento_descricao', models.TextField()),
                ('evento_descricao_curta', models.CharField(max_length=500)),
                ('evento_data_inicio', models.DateField()),
                ('evento_data_termino', models.DateField()),
                ('evento_foto', models.ImageField(blank=True, null=True, upload_to='evento')),
            ],
        ),
        migrations.CreateModel(
            name='PapelNoEvento',
            fields=[
                ('papel_id', models.AutoField(primary_key=True, serialize=False)),
                ('papel_nome', models.CharField(max_length=300)),
                ('papel_evento', models.ManyToManyField(blank=True, null=True, to='eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('pessoa_id', models.AutoField(primary_key=True, serialize=False)),
                ('pessoa_nome', models.CharField(max_length=300)),
                ('pessoa_sobrenome', models.CharField(max_length=300)),
                ('pessoa_email', models.CharField(max_length=300)),
                ('pessoa_bio', models.TextField()),
                ('pessoa_foto', models.ImageField(blank=True, null=True, upload_to='pessoa')),
                ('pessoa_papel', models.ManyToManyField(to='eventos.PapelNoEvento')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='atividade_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='atividade_pessoas',
            field=models.ManyToManyField(blank=True, null=True, to='eventos.Pessoa'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='atividade_tags',
            field=models.ManyToManyField(blank=True, null=True, to='eventos.Tag'),
        ),
    ]
