# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papelnoevento',
            name='papel_evento',
        ),
    ]
