# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_remove_papelnoevento_papel_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='evento_foto',
        ),
        migrations.AddField(
            model_name='evento',
            name='evento_banner',
            field=models.ImageField(blank=True, null=True, upload_to='evento_banner'),
        ),
        migrations.AddField(
            model_name='evento',
            name='evento_icone',
            field=models.ImageField(blank=True, null=True, upload_to='evento_icone'),
        ),
    ]
